name: Frontmatter to JSON
author: TheWolfNL
description: Convert frontmatter to a JSON string

branding:
  icon: file-text
  color: blue

inputs:
  content:
    description: content as a single string
    default: ""
  file:
    description: file path as a string
    default: ""

outputs:
  json:
    description: JSON object containing frontmatter
    value: ${{ steps.data.outputs.json }}

runs:
  using: composite
  steps:
    - id: file
      name: Read file to content
      if: inputs.file != ''
      shell: bash
      run: echo "content=$(jq -R < '${{ inputs.file }}')" >> $GITHUB_OUTPUT

    - id: data
      name: Extract frontmatter from content
      shell: bash
      run: |
        content=$(echo '${{ inputs.file != '' ? steps.file.outputs.content : inputs.content }}')
        JSON=$(jq -R <<< $content | jq -rs '.[0:([to_entries[] | select(.value == "---") | .key] | max)+1] | .[]' | yq 'select(. != null)' -o json | jq -c)
        echo 'Frontmatter:' 
        echo $JSON | jq
        echo "json=$JSON" >> $GITHUB_OUTPUT
