name: Frontmatter to JSON
author: TheWolfNL
description: Convert frontmatter to a JSON string

branding:
  icon: file-text
  color: blue

inputs:
  content:
    description: content as a single string
    default: ""
  file:
    description: file path as a string
    default: ""

outputs:
  json:
    description: JSON object containing frontmatter
    value: ${{ steps.data.outputs.json }}

runs:
  using: composite
  steps:
    - id: data
      name: Extract frontmatter from content
      shell: bash
      run: |
        if [ "${{ inputs.file }}" != '' ]; then
          JSON=$(jq -R < ${{ inputs.file }} | jq -rs '.[0:([to_entries[] | select(.value == "---") | .key] | max)+1] | .[]' | yq 'select(. != null)' -o json | jq -c)
        else
          JSON=$(echo "${{ inputs.content }}" | jq -R | jq -rs '.[0:([to_entries[] | select(.value == "---") | .key] | max)+1] | .[]' | yq 'select(. != null)' -o json | jq -c)
        fi
        if [ "$JSON" == '' ]; then
          JSON='{}'
        fi
        echo 'Frontmatter:' 
        echo $JSON | jq
        echo "json=$JSON" >> $GITHUB_OUTPUT
