name: Frontmatter to JSON
author: TheWolfNL
description: Convert frontmatter to a JSON string

branding:
  icon: file-text
  color: blue

inputs:
  content:
    description: content as a single string
    default: ""
  file:
    description: file path as a string
    default: ""

outputs:
  json:
    description: JSON object containing frontmatter
    value: ${{ steps.data.outputs.json }}

runs:
  using: composite
  steps:
    - id: file
      name: Read file to content
      if: inputs.file != ''
      shell: bash
      run: |
        set -eux
        < '${{ inputs.file }}' | sed 's/$/\\n/' | tr -d '\n'
        content=$(< '${{ inputs.file }}' | sed 's/$/\\n/' | tr -d '\n')
        sed 's/$/\\n/' < '${{ inputs.file }}' | tr -d '\n'
        echo 'Content:'
        echo $content
        echo "content=$content" >> $GITHUB_OUTPUT

    - id: data
      name: Extract frontmatter from content
      shell: bash
      run: |
        content=$(echo '${{ inputs.file != '' && steps.file.outputs.content || inputs.content }}')
        JSON=$(jq -R <<< $content | jq -rs '.[0:([to_entries[] | select(.value == "---") | .key] | max)+1] | .[]' | yq 'select(. != null)' -o json | jq -c)
        echo 'Frontmatter:' 
        echo $JSON | jq
        echo "json=$JSON" >> $GITHUB_OUTPUT
